"""Universal intelligence layer for recommendations and practice generation.

This module keeps vendor-specific logic out of the service layer by exposing a
provider protocol plus structured data contracts. Providers can be swapped via
configuration without changing recommendation workflows.
"""

from __future__ import annotations

import asyncio
from dataclasses import asdict, dataclass, field
import json
import logging
import threading
from typing import Any, Protocol, Sequence

import requests
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

from app.api.config import Settings
from app.api.perf_analytics import PerfAnalytics
from app.api.provider_health import ProviderHealth

logger = logging.getLogger(__name__)


@dataclass(frozen=True, slots=True)
class IntelligenceContext:
    """Normalized context passed to recommendation and practice engines."""

    user_id: str
    predicted_level: str
    source_text: str
    translated_text: str
    source_language: str
    target_language: str
    location: str | None = None
    environment: str | None = None
    sentiment: str | None = None
    intent: str | None = None
    ocr_text: str | None = None
    topic: str | None = None


@dataclass(frozen=True, slots=True)
class RecommendationDraft:
    """Candidate recommendation generated by an intelligence provider."""

    phrase: str
    meaning: str | None = None
    rationale: str | None = None
    confidence: float = 0.5


@dataclass(frozen=True, slots=True)
class CandidateSignal:
    """Features used by relevance assessment model."""

    candidate_key: str
    phrase: str
    vector_score: float | None = None
    lexical_score: float | None = None
    llm_score: float | None = None


@dataclass(frozen=True, slots=True)
class RelevanceDecision:
    """Relevance decision returned by model/evaluator."""

    candidate_key: str
    score: float
    approved: bool
    reason: str


@dataclass(frozen=True, slots=True)
class PracticeDraft:
    """Structured practice exercise returned by intelligence provider."""

    exercise_type: str
    prompt: str
    options: list[str] = field(default_factory=list)
    correct_answer: str | None = None
    explanation: str | None = None


class IntelligenceProvider(Protocol):
    """Provider contract for recommendation/practice intelligence."""

    async def generate_recommendations(
        self,
        context: IntelligenceContext,
        limit: int,
    ) -> list[RecommendationDraft]:
        """Generate draft recommendations from current context."""

        ...

    async def assess_relevance(
        self,
        context: IntelligenceContext,
        candidates: Sequence[CandidateSignal],
        approval_threshold: float,
    ) -> list[RelevanceDecision]:
        """Assess candidate relevance for the current user context."""

        ...

    async def generate_practice(
        self,
        context: IntelligenceContext,
        focus_terms: Sequence[str],
        limit: int,
    ) -> list[PracticeDraft]:
        """Generate structured multi-mode practice exercises."""

        ...

    def health_snapshot(self) -> dict[str, Any]:
        """Return current provider degradation/health metrics."""

        ...

    async def aclose(self) -> None:
        """Release provider resources."""

        ...


def _clamp01(value: float) -> float:
    return max(0.0, min(1.0, value))


def _tokens(text: str) -> set[str]:
    return {chunk for chunk in text.lower().replace("|", " ").split() if chunk}


def _build_retry_session() -> requests.Session:
    """Create a requests session with connection pooling and retries."""

    session = requests.Session()
    retry = Retry(
        total=3,
        connect=3,
        read=3,
        status=3,
        backoff_factor=0.4,
        status_forcelist=(429, 500, 502, 503, 504),
        allowed_methods=("POST",),
        raise_on_status=False,
    )
    adapter = HTTPAdapter(max_retries=retry, pool_connections=20, pool_maxsize=20)
    session.mount("http://", adapter)
    session.mount("https://", adapter)
    return session


class HeuristicIntelligenceProvider:
    """Deterministic fallback intelligence provider.

    This provider gives predictable behavior when external model APIs are
    unavailable and acts as a safe fallback for every remote call failure.
    """

    def __init__(self) -> None:
        self._health = ProviderHealth(
            name="intelligence",
            backend="heuristic",
            max_consecutive_failures=1,
        )

    async def generate_recommendations(
        self,
        context: IntelligenceContext,
        limit: int,
    ) -> list[RecommendationDraft]:
        templates = [
            (context.source_text, context.translated_text),
            (
                context.translated_text,
                f"Phrase used in {context.location or 'daily'} context.",
            ),
            (
                f"{context.translated_text} please",
                "Polite variation for student interactions.",
            ),
            (
                f"{context.translated_text} thank you",
                "Polite close for contextual conversations.",
            ),
            (
                context.source_text,
                "Original input retained for review and contrastive practice.",
            ),
        ]

        drafts: list[RecommendationDraft] = []
        seen: set[str] = set()
        for index, (phrase, meaning) in enumerate(templates, start=1):
            normalized_phrase = phrase.strip()
            if not normalized_phrase:
                continue
            key = normalized_phrase.lower()
            if key in seen:
                continue
            seen.add(key)
            confidence = _clamp01(0.88 - (index - 1) * 0.1)
            drafts.append(
                RecommendationDraft(
                    phrase=normalized_phrase,
                    meaning=meaning,
                    rationale="Heuristic candidate generated from active context.",
                    confidence=confidence,
                )
            )
            if len(drafts) >= limit:
                break
        self._health.record_success()
        return drafts

    async def assess_relevance(
        self,
        context: IntelligenceContext,
        candidates: Sequence[CandidateSignal],
        approval_threshold: float,
    ) -> list[RelevanceDecision]:
        context_tokens = _tokens(
            " ".join(
                chunk
                for chunk in [
                    context.source_text,
                    context.translated_text,
                    context.location or "",
                    context.environment or "",
                    context.intent or "",
                ]
            )
        )

        decisions: list[RelevanceDecision] = []
        for candidate in candidates:
            phrase_tokens = _tokens(candidate.phrase)
            overlap = 0.0
            if phrase_tokens and context_tokens:
                overlap = len(phrase_tokens & context_tokens) / len(phrase_tokens)

            vector_component = candidate.vector_score or 0.0
            lexical_component = candidate.lexical_score or 0.0
            llm_component = candidate.llm_score or 0.0

            score = _clamp01(
                0.40 * vector_component
                + 0.30 * lexical_component
                + 0.20 * llm_component
                + 0.10 * overlap
            )
            approved = score >= approval_threshold

            reason = (
                "Approved by heuristic relevance model."
                if approved
                else "Below heuristic relevance threshold; candidate can be regenerated."
            )
            decisions.append(
                RelevanceDecision(
                    candidate_key=candidate.candidate_key,
                    score=score,
                    approved=approved,
                    reason=reason,
                )
            )

        self._health.record_success()
        return decisions

    async def generate_practice(
        self,
        context: IntelligenceContext,
        focus_terms: Sequence[str],
        limit: int,
    ) -> list[PracticeDraft]:
        if not focus_terms:
            return []

        exercises: list[PracticeDraft] = []
        types_cycle = [
            "multiple_choice",
            "fill_in_the_blank",
            "translation",
            "open_response",
        ]

        for index, term in enumerate(focus_terms, start=1):
            exercise_type = types_cycle[(index - 1) % len(types_cycle)]
            if exercise_type == "multiple_choice":
                exercises.append(
                    PracticeDraft(
                        exercise_type="multiple_choice",
                        prompt=f"Choose the best contextual meaning for '{term}'.",
                        options=[
                            f"Contextual meaning of {term}",
                            f"Opposite of {term}",
                            f"Unrelated phrase near {context.location or 'campus'}",
                            f"Literal typo of {term}",
                        ],
                        correct_answer=f"Contextual meaning of {term}",
                        explanation="Multiple-choice review for contextual recall.",
                    )
                )
            elif exercise_type == "fill_in_the_blank":
                exercises.append(
                    PracticeDraft(
                        exercise_type="fill_in_the_blank",
                        prompt=f"Complete the sentence with '{term}': At the {context.location or 'university'}, I say ____.",
                        correct_answer=term,
                        explanation="Fill-in practice linked to current location context.",
                    )
                )
            elif exercise_type == "translation":
                exercises.append(
                    PracticeDraft(
                        exercise_type="translation",
                        prompt=f"Translate and include '{term}' in a sentence relevant to {context.environment or 'student life'}.",
                        correct_answer=None,
                        explanation="Open translation constrained by current context.",
                    )
                )
            else:
                exercises.append(
                    PracticeDraft(
                        exercise_type="open_response",
                        prompt=f"Write one realistic scenario in {context.location or 'daily life'} where '{term}' is useful.",
                        correct_answer=None,
                        explanation="Open-response contextual application exercise.",
                    )
                )

            if len(exercises) >= limit:
                break

        self._health.record_success()
        return exercises

    def health_snapshot(self) -> dict[str, Any]:
        return self._health.snapshot()

    async def aclose(self) -> None:
        return None


class GenericHttpIntelligenceProvider:
    """Generic HTTP intelligence provider.

    This provider sends structured tasks to an external model endpoint without
    hardcoding vendor SDKs. Any provider that can return JSON-compatible output
    can be integrated through configuration.
    """

    def __init__(
        self,
        *,
        api_key: str,
        completion_url: str,
        completion_model: str,
        timeout_seconds: float,
        strict_mode: bool = False,
        max_consecutive_failures: int = 5,
        fallback: IntelligenceProvider | None = None,
    ) -> None:
        if not api_key.strip():
            raise ValueError("LLM_API_KEY is required for generic_http intelligence backend.")

        self._api_key = api_key
        self._completion_url = completion_url
        self._completion_model = completion_model
        self._timeout_seconds = timeout_seconds
        self._strict_mode = strict_mode
        self._fallback = fallback or HeuristicIntelligenceProvider()
        self._session = _build_retry_session()
        self._session_lock = threading.Lock()
        self._health = ProviderHealth(
            name="intelligence",
            backend="generic_http",
            max_consecutive_failures=max_consecutive_failures,
        )

    @staticmethod
    def _serialize_context(context: IntelligenceContext) -> dict[str, Any]:
        return asdict(context)

    @staticmethod
    def _serialize_candidates(candidates: Sequence[CandidateSignal]) -> list[dict[str, Any]]:
        return [asdict(candidate) for candidate in candidates]

    async def generate_recommendations(
        self,
        context: IntelligenceContext,
        limit: int,
    ) -> list[RecommendationDraft]:
        payload = {
            "task": "generate_recommendations",
            "limit": limit,
            "context": self._serialize_context(context),
            "response_schema": {
                "recommendations": [
                    {
                        "phrase": "string",
                        "meaning": "string|null",
                        "rationale": "string|null",
                        "confidence": "float(0..1)",
                    }
                ]
            },
        }
        try:
            data = await asyncio.to_thread(self._request_json_sync, payload)
            recommendations = data.get("recommendations", [])
            parsed: list[RecommendationDraft] = []
            for raw in recommendations:
                phrase = str(raw.get("phrase", "")).strip()
                if not phrase:
                    continue
                parsed.append(
                    RecommendationDraft(
                        phrase=phrase,
                        meaning=(
                            str(raw.get("meaning")).strip()
                            if raw.get("meaning") is not None
                            else None
                        ),
                        rationale=(
                            str(raw.get("rationale")).strip()
                            if raw.get("rationale") is not None
                            else None
                        ),
                        confidence=_clamp01(float(raw.get("confidence", 0.5))),
                    )
                )
            if parsed:
                self._health.record_success()
                return parsed[:limit]
        except (requests.RequestException, json.JSONDecodeError, ValueError, KeyError, TypeError) as exc:
            self._health.record_failure(exc)
            if self._strict_mode and self._health.should_fail_fast():
                raise RuntimeError(
                    "generic_http intelligence provider entered fail-fast mode"
                ) from exc
            logger.warning("Generic intelligence recommendation call failed: %s", exc)

        return await self._fallback.generate_recommendations(context, limit)

    async def assess_relevance(
        self,
        context: IntelligenceContext,
        candidates: Sequence[CandidateSignal],
        approval_threshold: float,
    ) -> list[RelevanceDecision]:
        payload = {
            "task": "assess_relevance",
            "approval_threshold": approval_threshold,
            "context": self._serialize_context(context),
            "candidates": self._serialize_candidates(candidates),
            "response_schema": {
                "assessments": [
                    {
                        "candidate_key": "string",
                        "score": "float(0..1)",
                        "approved": "boolean",
                        "reason": "string",
                    }
                ]
            },
        }
        try:
            data = await asyncio.to_thread(self._request_json_sync, payload)
            assessments = data.get("assessments", [])
            parsed: list[RelevanceDecision] = []
            for raw in assessments:
                candidate_key = str(raw.get("candidate_key", "")).strip()
                if not candidate_key:
                    continue
                score = _clamp01(float(raw.get("score", 0.0)))
                approved = bool(raw.get("approved", score >= approval_threshold))
                reason = str(raw.get("reason", "Model relevance assessment.")).strip()
                parsed.append(
                    RelevanceDecision(
                        candidate_key=candidate_key,
                        score=score,
                        approved=approved,
                        reason=reason,
                    )
                )
            if parsed:
                self._health.record_success()
                return parsed
        except (requests.RequestException, json.JSONDecodeError, ValueError, KeyError, TypeError) as exc:
            self._health.record_failure(exc)
            if self._strict_mode and self._health.should_fail_fast():
                raise RuntimeError(
                    "generic_http intelligence provider entered fail-fast mode"
                ) from exc
            logger.warning("Generic intelligence relevance call failed: %s", exc)

        return await self._fallback.assess_relevance(
            context,
            candidates,
            approval_threshold,
        )

    async def generate_practice(
        self,
        context: IntelligenceContext,
        focus_terms: Sequence[str],
        limit: int,
    ) -> list[PracticeDraft]:
        payload = {
            "task": "generate_practice",
            "limit": limit,
            "context": self._serialize_context(context),
            "focus_terms": list(focus_terms),
            "response_schema": {
                "exercises": [
                    {
                        "exercise_type": "multiple_choice|fill_in_the_blank|translation|open_response",
                        "prompt": "string",
                        "options": ["string"],
                        "correct_answer": "string|null",
                        "explanation": "string|null",
                    }
                ]
            },
        }
        try:
            data = await asyncio.to_thread(self._request_json_sync, payload)
            exercises = data.get("exercises", [])
            parsed: list[PracticeDraft] = []
            for raw in exercises:
                exercise_type = str(raw.get("exercise_type", "")).strip()
                prompt = str(raw.get("prompt", "")).strip()
                if not exercise_type or not prompt:
                    continue
                options_raw = raw.get("options", [])
                options = [str(option) for option in options_raw] if isinstance(options_raw, list) else []
                correct_answer = (
                    str(raw.get("correct_answer")).strip()
                    if raw.get("correct_answer") is not None
                    else None
                )
                explanation = (
                    str(raw.get("explanation")).strip()
                    if raw.get("explanation") is not None
                    else None
                )
                parsed.append(
                    PracticeDraft(
                        exercise_type=exercise_type,
                        prompt=prompt,
                        options=options,
                        correct_answer=correct_answer,
                        explanation=explanation,
                    )
                )
            if parsed:
                self._health.record_success()
                return parsed[:limit]
        except (requests.RequestException, json.JSONDecodeError, ValueError, KeyError, TypeError) as exc:
            self._health.record_failure(exc)
            if self._strict_mode and self._health.should_fail_fast():
                raise RuntimeError(
                    "generic_http intelligence provider entered fail-fast mode"
                ) from exc
            logger.warning("Generic intelligence practice call failed: %s", exc)

        return await self._fallback.generate_practice(context, focus_terms, limit)

    def _request_json_sync(self, payload: dict[str, Any]) -> dict[str, Any]:
        analytics = PerfAnalytics(
            logger=logger,
            scope="generic_http_intelligence.request_json_sync",
            context={
                "task": str(payload.get("task") or "unknown"),
                "model": self._completion_model,
            },
        )

        request_body = {
            "model": self._completion_model,
            "messages": [
                {
                    "role": "system",
                    "content": (
                        "You are a language-learning recommendation engine. "
                        "Return a strict JSON object only."
                    ),
                },
                {
                    "role": "user",
                    "content": json.dumps(payload),
                },
            ],
            "temperature": 0.2,
            "response_format": {"type": "json_object"},
        }

        try:
            with analytics.stage("http_post", kind="network"):
                with self._session_lock:
                    response = self._session.post(
                        self._completion_url,
                        headers={
                            "Authorization": f"Bearer {self._api_key}",
                            "Content-Type": "application/json",
                        },
                        json=request_body,
                        timeout=self._timeout_seconds,
                    )
                response.raise_for_status()

            with analytics.stage("parse_provider_payload", kind="compute"):
                raw = response.json()
                return self._extract_json_object(raw)
        finally:
            analytics.log_summary()

    @staticmethod
    def _extract_json_object(raw: Any) -> dict[str, Any]:
        if isinstance(raw, dict):
            if isinstance(raw.get("output"), dict):
                return raw["output"]
            if isinstance(raw.get("json"), dict):
                return raw["json"]
            if isinstance(raw.get("data"), dict):
                return raw["data"]

            choices = raw.get("choices")
            if isinstance(choices, list) and choices:
                message = choices[0].get("message", {})
                content = message.get("content")
                parsed = GenericHttpIntelligenceProvider._parse_content(content)
                if parsed:
                    return parsed

            candidates = raw.get("candidates")
            if isinstance(candidates, list) and candidates:
                content = candidates[0].get("content", {})
                parts = content.get("parts", [])
                if isinstance(parts, list) and parts:
                    text_part = parts[0].get("text")
                    parsed = GenericHttpIntelligenceProvider._parse_content(text_part)
                    if parsed:
                        return parsed

        raise ValueError("Unable to extract JSON payload from provider response.")

    @staticmethod
    def _parse_content(content: Any) -> dict[str, Any] | None:
        if isinstance(content, dict):
            return content
        if isinstance(content, list):
            chunks: list[str] = []
            for item in content:
                if isinstance(item, dict) and item.get("type") == "text":
                    text_value = item.get("text")
                    if isinstance(text_value, str):
                        chunks.append(text_value)
                elif isinstance(item, str):
                    chunks.append(item)
            if chunks:
                content = "\n".join(chunks)
            else:
                return None
        if isinstance(content, str):
            cleaned = content.strip()
            if cleaned.startswith("```"):
                cleaned = cleaned.replace("```json", "", 1).replace("```", "").strip()
            parsed = json.loads(cleaned)
            if isinstance(parsed, dict):
                return parsed
        return None

    def health_snapshot(self) -> dict[str, Any]:
        return self._health.snapshot()

    async def aclose(self) -> None:
        await asyncio.to_thread(self._session.close)


def build_intelligence_provider(settings: Settings) -> IntelligenceProvider:
    """Build intelligence provider from runtime settings."""

    backend = settings.intelligence_backend.strip().lower()
    if backend == "generic_http":
        try:
            provider = GenericHttpIntelligenceProvider(
                api_key=settings.llm_api_key,
                completion_url=settings.llm_completion_url,
                completion_model=settings.llm_completion_model,
                timeout_seconds=settings.llm_completion_timeout_seconds,
                strict_mode=settings.provider_strict_mode,
                max_consecutive_failures=settings.provider_max_consecutive_failures,
            )
            logger.info(
                "Using generic_http intelligence backend with model '%s'",
                settings.llm_completion_model,
            )
            return provider
        except (ValueError, TypeError) as exc:
            if settings.provider_strict_mode:
                raise RuntimeError(
                    "Failed to initialize generic_http intelligence provider in strict mode."
                ) from exc
            logger.warning(
                "Falling back to heuristic intelligence backend. generic_http init failed: %s",
                exc,
            )

    return HeuristicIntelligenceProvider()
